import React, { useEffect, useState } from "react";
import { Navigate } from "react-router-dom";
import { api, asArray, formatApiError } from "@/lib/api";
import { useAuth } from "@/contexts/AuthContext";
import { useOrganization } from "@/contexts/OrganizationContext";
import { displayOrganizationName } from "@/lib/organizationDisplay";
import { Building2, CheckCircle2, CircleAlert, FileText, KeyRound, Pencil, Plus, ShieldCheck, Users2 } from "lucide-react";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { toast } from "sonner";

const freshOrg = { name: "", slug: "", active: true };
const freshUser = { name: "", email: "", password: "", role: "executive", organization_id: "", active: true };
const freshTemplate = { channel: "email", name: "", subject: "", body: "" };

function TextField({ label, value, setValue, type = "text", placeholder = "" }) {
  return <label className="block"><span className="label-caps mb-1.5 block">{label}</span><input type={type} value={value || ""} onChange={(e) => setValue(e.target.value)} placeholder={placeholder} className="w-full h-10 border border-[#E6E4DD] rounded-sm px-3 text-sm focus:outline-none focus:border-forest" /></label>;
}
function Metric({ label, value, Icon }) { return <div className="border border-[#E6E4DD] bg-white rounded-sm p-5"><div className="flex justify-between"><span className="label-caps">{label}</span><Icon className="h-4 w-4 text-forest/50" /></div><div className="font-display font-black text-4xl text-forest mt-2 tabular-nums">{value || 0}</div></div>; }

export default function SuperAdmin() {
  const { user } = useAuth();
  const { organizations, activeOrganization, activeOrganizationId, refreshOrganizations, setActiveOrganization } = useOrganization();
  const [overview, setOverview] = useState({ organizations: [], totals: {} });
  const [members, setMembers] = useState([]);
  const [templates, setTemplates] = useState([]);
  const [audit, setAudit] = useState([]);
  const [integration, setIntegration] = useState({});
  const [orgForm, setOrgForm] = useState(freshOrg), [editingOrg, setEditingOrg] = useState(null), [orgOpen, setOrgOpen] = useState(false);
  const [userForm, setUserForm] = useState(freshUser), [editingUser, setEditingUser] = useState(null), [userOpen, setUserOpen] = useState(false);
  const [templateForm, setTemplateForm] = useState(freshTemplate), [editingTemplate, setEditingTemplate] = useState(null), [templateOpen, setTemplateOpen] = useState(false);
  const [integrationOpen, setIntegrationOpen] = useState(false), [busy, setBusy] = useState(false);

  const load = async () => {
    try {
      const [overviewResult, userResult] = await Promise.all([api.get("/super-admin/overview"), api.get("/users")]);
      setOverview(overviewResult.data || { organizations: [], totals: {} }); setMembers(asArray(userResult.data)); await refreshOrganizations();
    } catch (e) { toast.error(formatApiError(e.response?.data?.detail) || "Could not load Super Admin data"); }
  };
  const loadOrganization = async () => {
    if (!activeOrganizationId) return;
    try {
      const [t, i, a] = await Promise.all([api.get(`/organizations/${activeOrganizationId}/templates`), api.get(`/organizations/${activeOrganizationId}/integration`), api.get("/super-admin/audit-logs", { params: { organization_id: activeOrganizationId } })]);
      setTemplates(asArray(t.data)); setIntegration(i.data || {}); setAudit(asArray(a.data));
    } catch (e) { toast.error(formatApiError(e.response?.data?.detail) || "Could not load organisation details"); }
  };
  useEffect(() => { if (user?.role === "super_admin") load(); }, [user]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { loadOrganization(); }, [activeOrganizationId]); // eslint-disable-line react-hooks/exhaustive-deps
  if (user?.role !== "super_admin") return <Navigate to="/" replace />;

  const save = async (action) => { setBusy(true); try { await action(); } catch (e) { toast.error(formatApiError(e.response?.data?.detail) || "Could not save changes"); } finally { setBusy(false); } };
  const saveOrg = () => save(async () => { if (!orgForm.name || !orgForm.slug) throw new Error("Name and slug are required"); if (editingOrg) await api.patch(`/organizations/${editingOrg.id}`, orgForm); else await api.post("/organizations", orgForm); toast.success("Organisation saved"); setOrgOpen(false); await load(); });
  const saveUser = () => save(async () => { if (!userForm.name || !userForm.email || !userForm.organization_id || (!editingUser && !userForm.password)) throw new Error("Name, email, organisation and temporary password are required"); if (editingUser) { const p = { name: userForm.name, role: userForm.role, organization_id: userForm.organization_id, active: userForm.active }; if (userForm.password) p.password = userForm.password; await api.patch(`/users/${editingUser.id}`, p); } else await api.post("/users", userForm); toast.success("Member saved"); setUserOpen(false); await load(); });
  const saveIntegration = () => save(async () => { const payload = { ...integration }; ["resend_api_key", "whatsapp_access_token", "portal_api_key"].forEach((key) => { if (!payload[key]) delete payload[key]; }); await api.put(`/organizations/${activeOrganizationId}/integration`, payload); toast.success("Delivery configuration saved"); setIntegrationOpen(false); await load(); await loadOrganization(); });
  const saveTemplate = () => save(async () => { if (!templateForm.name || !templateForm.body) throw new Error("Template name and body are required"); if (editingTemplate) await api.patch(`/organizations/${activeOrganizationId}/templates/${editingTemplate.id}`, templateForm); else await api.post(`/organizations/${activeOrganizationId}/templates`, templateForm); toast.success("Template saved"); setTemplateOpen(false); await loadOrganization(); });
  const deleteTemplate = async (template) => { if (!window.confirm(`Delete ${template.name}?`)) return; try { await api.delete(`/organizations/${activeOrganizationId}/templates/${template.id}`); toast.success("Template deleted"); await loadOrganization(); } catch (e) { toast.error(formatApiError(e.response?.data?.detail)); } };
  const updateIntegration = (key, value) => setIntegration({ ...integration, [key]: value });

  return <div className="space-y-6">
    <div className="flex items-start justify-between gap-4 flex-wrap"><div><div className="label-caps">Platform control</div><h1 className="font-display font-black text-3xl text-forest tracking-tight mt-1">Super Admin</h1><p className="text-sm text-forest/60 mt-1">Organisation, user, delivery and template control for Propzel.</p></div><div className="flex gap-2"><button onClick={() => { setEditingOrg(null); setOrgForm(freshOrg); setOrgOpen(true); }} className="h-9 px-3.5 rounded-sm bg-forest text-white text-sm inline-flex items-center gap-2"><Plus className="h-4 w-4" /> Organisation</button><button onClick={() => { setEditingUser(null); setUserForm({ ...freshUser, organization_id: activeOrganizationId }); setUserOpen(true); }} className="h-9 px-3.5 rounded-sm border border-[#E6E4DD] bg-white text-sm inline-flex items-center gap-2"><Plus className="h-4 w-4" /> User</button></div></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Metric label="Organisations" value={overview.totals?.organizations} Icon={Building2} /><Metric label="Users" value={overview.totals?.users} Icon={Users2} /><Metric label="Leads" value={overview.totals?.leads} Icon={ShieldCheck} /><Metric label="Activities" value={overview.totals?.activities} Icon={FileText} /></div>

    <section className="border border-[#E6E4DD] bg-white rounded-sm overflow-hidden"><div className="px-5 py-4 border-b border-[#E6E4DD] bg-bone-alt/40 font-display font-bold text-lg text-forest">Organisation dashboard</div><div className="divide-y divide-[#E6E4DD]">{overview.organizations.map((org) => <div key={org.id} className="p-5 grid grid-cols-1 xl:grid-cols-[1fr_1.6fr_auto] gap-5 items-center"><div><div className="flex items-center gap-2"><b className="font-display text-xl text-forest">{displayOrganizationName(org.name)}</b><span className={org.active === false ? "text-xs text-clay" : "text-xs text-[#2D6A4F]"}>{org.active === false ? "Inactive" : "Active"}</span></div><div className="text-xs text-forest/50 mt-1">{org.slug}</div></div><div className="grid grid-cols-3 md:grid-cols-6 gap-3">{Object.entries(org.stats || {}).map(([key, value]) => <div key={key} className="text-center"><div className="font-display font-bold text-lg text-forest">{value}</div><div className="text-[9px] uppercase tracking-[0.1em] text-forest/50">{key.replace("_", " ")}</div></div>)}</div><div className="flex gap-2"><button onClick={() => setActiveOrganization(org.id)} className="h-9 px-3 border border-[#E6E4DD] rounded-sm text-sm">Open</button><button onClick={() => { setEditingOrg(org); setOrgForm({ name: org.name, slug: org.slug, active: org.active !== false }); setOrgOpen(true); }} className="h-9 w-9 bg-forest text-white rounded-sm grid place-items-center"><Pencil className="h-3.5 w-3.5" /></button></div><div className="xl:col-span-3 text-xs flex gap-3"><span className={org.integration?.resend_api_key_configured && org.integration?.resend_domain_verified ? "text-[#2D6A4F]" : "text-clay"}>{org.integration?.resend_api_key_configured && org.integration?.resend_domain_verified ? <CheckCircle2 className="h-3.5 w-3.5 inline mr-1" /> : <CircleAlert className="h-3.5 w-3.5 inline mr-1" />}Email</span><span className={org.integration?.whatsapp_access_token_configured && org.integration?.whatsapp_instance_id ? "text-[#2D6A4F]" : "text-clay"}>{org.integration?.whatsapp_access_token_configured && org.integration?.whatsapp_instance_id ? <CheckCircle2 className="h-3.5 w-3.5 inline mr-1" /> : <CircleAlert className="h-3.5 w-3.5 inline mr-1" />}WhatsApp</span></div></div>)}</div></section>

    <section className="border border-[#E6E4DD] bg-white rounded-sm overflow-hidden"><div className="px-5 py-4 border-b border-[#E6E4DD] bg-bone-alt/40 flex justify-between"><div><div className="font-display font-bold text-lg text-forest">{displayOrganizationName(activeOrganization?.name) || "Organisation"} configuration</div><div className="text-xs text-forest/50 mt-1">WhatsApp and Resend are stored server-side for this organisation.</div></div><button disabled={!activeOrganizationId} onClick={() => setIntegrationOpen(true)} className="h-9 px-3 rounded-sm border border-[#E6E4DD] text-sm disabled:opacity-50 inline-flex items-center gap-2"><KeyRound className="h-3.5 w-3.5" /> Manage</button></div><div className="p-5 grid grid-cols-2 gap-5"><div><div className="label-caps">WhatsApp</div><div className="text-sm text-forest mt-1">{integration.whatsapp_number || "Not configured"}</div></div><div><div className="label-caps">Email / Resend</div><div className="text-sm text-forest mt-1">{integration.resend_from_email || "Not configured"}</div></div></div></section>

    <section className="border border-[#E6E4DD] bg-white rounded-sm overflow-hidden"><div className="px-5 py-4 border-b border-[#E6E4DD] bg-bone-alt/40 font-display font-bold text-lg text-forest">Users</div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="text-[10px] uppercase tracking-[0.15em] text-forest/60"><tr><th className="text-left px-5 py-3">Member</th><th className="text-left px-5 py-3">Role</th><th className="text-left px-5 py-3">Organisation</th><th className="text-left px-5 py-3">Status</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y divide-[#E6E4DD]">{members.map((member) => <tr key={member.id}><td className="px-5 py-3"><b className="font-medium text-forest">{member.name}</b><div className="text-xs text-forest/50">{member.email}</div></td><td className="px-5 py-3 capitalize">{member.role.replace("_", " ")}</td><td className="px-5 py-3">{member.role === "super_admin" ? "All organisations" : displayOrganizationName(organizations.find((org) => org.id === member.organization_id)?.name) || "Unassigned"}</td><td className="px-5 py-3"><span className={member.active === false ? "text-clay" : "text-[#2D6A4F]"}>{member.active === false ? "Inactive" : "Active"}</span></td><td className="px-5 py-3 text-right">{member.role !== "super_admin" && <button onClick={() => { setEditingUser(member); setUserForm({ name: member.name, email: member.email, password: "", role: member.role, organization_id: member.organization_id, active: member.active !== false }); setUserOpen(true); }} className="h-8 w-8 border border-[#E6E4DD] rounded-sm inline-grid place-items-center"><Pencil className="h-3.5 w-3.5" /></button>}</td></tr>)}</tbody></table></div></section>

    <section className="border border-[#E6E4DD] bg-white rounded-sm overflow-hidden"><div className="px-5 py-4 border-b border-[#E6E4DD] bg-bone-alt/40 flex justify-between"><div className="font-display font-bold text-lg text-forest">Templates</div><button disabled={!activeOrganizationId} onClick={() => { setEditingTemplate(null); setTemplateForm(freshTemplate); setTemplateOpen(true); }} className="h-9 px-3 rounded-sm bg-forest text-white text-sm disabled:opacity-50">New template</button></div><div className="divide-y divide-[#E6E4DD]">{templates.map((template) => <div key={template.id} className="p-4 flex gap-4 items-center"><span className="text-[10px] uppercase tracking-[0.14em] text-forest/60 w-20">{template.channel}</span><div className="flex-1 min-w-0"><b className="font-medium text-forest">{template.name}</b><div className="text-xs text-forest/50 truncate">{template.subject || template.body}</div></div><button onClick={() => { setEditingTemplate(template); setTemplateForm({ channel: template.channel, name: template.name, subject: template.subject || "", body: template.body }); setTemplateOpen(true); }} className="text-xs text-forest">Edit</button><button onClick={() => deleteTemplate(template)} className="text-xs text-clay">Delete</button></div>)}{!templates.length && <div className="p-6 text-sm text-forest/50">No templates configured.</div>}</div></section>
    <section className="border border-[#E6E4DD] bg-white rounded-sm overflow-hidden"><div className="px-5 py-4 border-b border-[#E6E4DD] bg-bone-alt/40 font-display font-bold text-lg text-forest">Audit log</div><div className="divide-y divide-[#E6E4DD]">{audit.slice(0, 8).map((item) => <div className="px-5 py-3 text-sm" key={item.id}><b className="font-medium text-forest">{item.message}</b><span className="text-xs text-forest/50 ml-2">{item.created_at && new Date(item.created_at).toLocaleString()}</span></div>)}{!audit.length && <div className="p-6 text-sm text-forest/50">No organisation audit activity yet.</div>}</div></section>

    <Dialog open={orgOpen} onOpenChange={setOrgOpen}><DialogContent className="rounded-sm"><DialogHeader><DialogTitle>{editingOrg ? "Edit organisation" : "Create organisation"}</DialogTitle></DialogHeader><div className="space-y-3"><TextField label="Name" value={orgForm.name} setValue={(name) => setOrgForm({ ...orgForm, name })} /><TextField label="Slug" value={orgForm.slug} setValue={(slug) => setOrgForm({ ...orgForm, slug: slug.toLowerCase().replace(/[^a-z0-9-]/g, "-") })} /><div className="flex justify-between border border-[#E6E4DD] rounded-sm px-3 py-2"><span className="text-sm">Active</span><Switch checked={orgForm.active} onCheckedChange={(active) => setOrgForm({ ...orgForm, active })} /></div></div><DialogFooter><button disabled={busy} onClick={saveOrg} className="h-9 px-4 bg-forest text-white rounded-sm text-sm">Save</button></DialogFooter></DialogContent></Dialog>
    <Dialog open={userOpen} onOpenChange={setUserOpen}><DialogContent className="rounded-sm"><DialogHeader><DialogTitle>{editingUser ? "Edit user" : "Create user"}</DialogTitle></DialogHeader><div className="space-y-3"><TextField label="Name" value={userForm.name} setValue={(name) => setUserForm({ ...userForm, name })} /><TextField label="Email" type="email" value={userForm.email} setValue={(email) => setUserForm({ ...userForm, email })} /><TextField label={editingUser ? "Reset password" : "Temporary password"} type="password" value={userForm.password} setValue={(password) => setUserForm({ ...userForm, password })} /><label className="block"><span className="label-caps mb-1.5 block">Role</span><Select value={userForm.role} onValueChange={(role) => setUserForm({ ...userForm, role })}><SelectTrigger className="h-10"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="admin">Admin</SelectItem><SelectItem value="manager">Manager</SelectItem><SelectItem value="executive">Executive</SelectItem></SelectContent></Select></label><label className="block"><span className="label-caps mb-1.5 block">Organisation</span><Select value={userForm.organization_id || "__none__"} onValueChange={(organization_id) => setUserForm({ ...userForm, organization_id: organization_id === "__none__" ? "" : organization_id })}><SelectTrigger className="h-10"><SelectValue /></SelectTrigger><SelectContent>{organizations.map((org) => <SelectItem value={org.id} key={org.id}>{displayOrganizationName(org.name)}</SelectItem>)}</SelectContent></Select></label>{editingUser && <div className="flex justify-between border border-[#E6E4DD] rounded-sm px-3 py-2"><span className="text-sm">Active</span><Switch checked={userForm.active} onCheckedChange={(active) => setUserForm({ ...userForm, active })} /></div>}</div><DialogFooter><button disabled={busy} onClick={saveUser} className="h-9 px-4 bg-forest text-white rounded-sm text-sm">Save</button></DialogFooter></DialogContent></Dialog>
    <Dialog open={integrationOpen} onOpenChange={setIntegrationOpen}><DialogContent className="rounded-sm max-w-2xl"><DialogHeader><DialogTitle>{displayOrganizationName(activeOrganization?.name)} delivery configuration</DialogTitle></DialogHeader><div className="grid md:grid-cols-2 gap-3"><TextField label="WhatsApp provider" value={integration.whatsapp_provider} setValue={(v) => updateIntegration("whatsapp_provider", v)} /><TextField label="WhatsApp number" value={integration.whatsapp_number} setValue={(v) => updateIntegration("whatsapp_number", v)} /><TextField label="Service URL" value={integration.whatsapp_service_url} setValue={(v) => updateIntegration("whatsapp_service_url", v)} /><TextField label="Instance ID" value={integration.whatsapp_instance_id} setValue={(v) => updateIntegration("whatsapp_instance_id", v)} /><TextField label="Access token" type="password" placeholder={integration.whatsapp_access_token_configured ? "Configured - enter to replace" : "Provider token"} value={integration.whatsapp_access_token} setValue={(v) => updateIntegration("whatsapp_access_token", v)} /><TextField label="Resend sender" value={integration.resend_from_email} setValue={(v) => updateIntegration("resend_from_email", v)} /><TextField label="Resend domain" value={integration.resend_domain} setValue={(v) => updateIntegration("resend_domain", v)} /><TextField label="Resend API key" type="password" placeholder={integration.resend_api_key_configured ? "Configured - enter to replace" : "Resend key"} value={integration.resend_api_key} setValue={(v) => updateIntegration("resend_api_key", v)} /></div><div className="flex justify-between border border-[#E6E4DD] rounded-sm px-3 py-2"><span className="text-sm">Resend domain verified</span><Switch checked={!!integration.resend_domain_verified} onCheckedChange={(v) => updateIntegration("resend_domain_verified", v)} /></div><DialogFooter><button disabled={busy} onClick={saveIntegration} className="h-9 px-4 bg-forest text-white rounded-sm text-sm">Save configuration</button></DialogFooter></DialogContent></Dialog>
    <Dialog open={templateOpen} onOpenChange={setTemplateOpen}><DialogContent className="rounded-sm"><DialogHeader><DialogTitle>{editingTemplate ? "Edit template" : "Create template"}</DialogTitle></DialogHeader><div className="space-y-3"><label className="block"><span className="label-caps mb-1.5 block">Channel</span><Select value={templateForm.channel} onValueChange={(channel) => setTemplateForm({ ...templateForm, channel })}><SelectTrigger className="h-10"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="email">Email</SelectItem><SelectItem value="whatsapp">WhatsApp</SelectItem></SelectContent></Select></label><TextField label="Name" value={templateForm.name} setValue={(name) => setTemplateForm({ ...templateForm, name })} />{templateForm.channel === "email" && <TextField label="Subject" value={templateForm.subject} setValue={(subject) => setTemplateForm({ ...templateForm, subject })} />}<label className="block"><span className="label-caps mb-1.5 block">Body</span><textarea value={templateForm.body} onChange={(e) => setTemplateForm({ ...templateForm, body: e.target.value })} className="w-full min-h-32 border border-[#E6E4DD] rounded-sm p-3 text-sm" /></label></div><DialogFooter><button disabled={busy} onClick={saveTemplate} className="h-9 px-4 bg-forest text-white rounded-sm text-sm">Save template</button></DialogFooter></DialogContent></Dialog>
  </div>;
}
